frontend/linki-user/src/api/campaign.js, frontend/linki-user/src/api/proposal.js, frontend/linki-user/src/router/index.js, frontend/linki-user/src/utils/httpRequest.js
---
name: PR template
about: PR template
title: ''
labels: ''
assignees: ''
---
공통으로 사용하는 router 폴더 index.js 수정
백엔드와 api 경로 통일 
json 서버는 3000번으로 통일해야 할듯
코드 스타일이 달라서 추후에 한번 통일하는 과정 필요
=> 🐛 fix : 라우터 설정 관련 오류 수정

frontend/linki-admin/src/components/Sidebar.vue, frontend/linki-admin/src/components/table/SettlementTable.vue, frontend/linki-admin/src/components/table/SubscriptionPaymentTable.vue, frontend/linki-admin/src/js/Settlement.js, frontend/linki-admin/src/js/SubscriptionPayment.js, frontend/linki-admin/src/libs/httpRequester.js, frontend/linki-admin/src/router/index.js, frontend/linki-admin/src/views/admin/SettlementView.vue, frontend/linki-admin/src/views/admin/SubscriptionPaymentView.vue
관리자-정산,구독 관리 프론트 페이지 구현
@dlwjdtjq001 정산 완료 버튼 클릭 시 처리 로직 구현 예정
=> ✨ feature : 관리자-정산,구독 관리 프론트 페이지 구현

frontend/linki-admin/package-lock.json, frontend/linki-admin/package.json, frontend/linki-admin/src/components/MyPage/MyPageProfile.vue, frontend/linki-admin/src/components/MyPage/MyPageSidebar.vue, frontend/linki-admin/src/components/MyPage/MypagePassword.vue, frontend/linki-admin/src/components/Sidebar.vue, frontend/linki-admin/src/js/Admin.js, frontend/linki-admin/src/js/Dashboard.js, frontend/linki-admin/src/main.js, frontend/linki-admin/src/router/index.js, frontend/linki-admin/src/views/HomeView.vue, frontend/linki-admin/src/views/admin/AdminApprovalView.vue, frontend/linki-admin/src/views/admin/mypage/MyPage.vue, frontend/linki-admin/src/views/admin/mypage/MyPagePasswordView.vue, frontend/linki-admin/src/views/admin/mypage/MyPageProfileView.vue, frontend/linki-admin/src/views/admin/operations/AdminReviews.vue, frontend/linki-admin/src/views/admin/operations/AdminSignUp.vue, frontend/linki-admin/src/views/admin/operations/influencerReviews.vue
=> ✨ feature : 관리자 대시보드 프론트 페이지 구현

linki-api/build.gradle, linki-api/src/main/java/com/Gritty/Linki/util/IdGenerator.java, linki-api/src/test/java/com/Gritty/Linki/util/IdGeneratorTest.java
ID Generator 추가
static으로 만들어서 바로 호출 가능
ex)
```
String userId = IdGenerator.userId();
String authId = IdGenerator.authId();
String statsId = IdGenerator.statsId();
String channelId = IdGenerator.channelId();
String influencerId = IdGenerator.influencerId();
String advertiserId = IdGenerator.advertiserId();
String campaignId = IdGenerator.campaignId();
String proposalId = IdGenerator.proposalId();
String contractId = IdGenerator.contractId();
String signatureId = IdGenerator.signatureId();
String influencerReviewId = IdGenerator.influencerReviewId();
String advertiserReviewId = IdGenerator.advertiserReviewId();
String adminId = IdGenerator.adminId();
String chatId = IdGenerator.chatId();
String chatAlarmId = IdGenerator.chatAlarmId();
String subscribeId = IdGenerator.subscribeId();
String …
```
=> ✨ feature : ID Generator 추가

frontend/linki-admin/src/components/MyPage/MyPageProfile.vue, frontend/linki-admin/src/components/MyPage/MypagePassword.vue, frontend/linki-user/src/components/user/influencer/mypage/MyPageBasicInfo.vue, frontend/linki-user/src/components/user/influencer/mypage/MyPagePassword.vue, frontend/linki-user/src/components/user/influencer/mypage/MyPageSideBar.vue, frontend/linki-user/src/views/user/influencer/MyPage.vue
마이페이지(프로필, 비밀번호변경) 작업
- 유저 마이페이지(프로필, 비밀번호변경)
- 관리자 마이페이지 (프로필, 비밀번호변경)
예상되는 영향이나 고민
=> feature : 관리자, 유저 마이페이지 (프로필, 비밀번호변경) 작업

frontend/linki-user/src/api/campaign.js, frontend/linki-user/src/components/user/advertiser/mypage/MyPageCompletedContracts.vue, frontend/linki-user/src/components/user/advertiser/mypage/MyPageOngoingContracts.vue, frontend/linki-user/src/components/user/influencer/mypage/MyPageCompletedContracts.vue, frontend/linki-user/src/components/user/influencer/mypage/MyPageOngoingContracts.vue, frontend/linki-user/src/components/user/influencer/mypage/MyPageSettlement.vue, frontend/linki-user/src/views/user/influencer/CampaignDetailView.vue
pending-sign(서명대기 추가), 디자인 작업
- 서명 대기 상태 추가
- 계약 관리 메뉴 디자인 변경 
예상되는 영향이나 고민
=> ✨ feature : pending-sign(서명대기 추가), 디자인 작업

frontend/linki-admin/vite.config.js, frontend/linki-user/vite.config.js
프론트 외부 접속 가능 설정
- 프론트 외부 접속 가능 설정
예상되는 영향이나 고민
=> 🔧 chore : 프론트 외부 접속 가능 설정

frontend/linki-user/src/api/campaign.js, frontend/linki-user/src/api/contract.js, frontend/linki-user/src/api/proposal.js, frontend/linki-user/src/api/review.js, frontend/linki-user/src/components/user/influencer/detail/DetailCampaign.vue, frontend/linki-user/src/components/user/influencer/detail/DetailContract.vue, frontend/linki-user/src/components/user/influencer/detail/DetailProposal.vue, frontend/linki-user/src/components/user/influencer/detail/ProposalDetailView.vue, frontend/linki-user/src/components/user/influencer/mypage/MyPageProposalList.vue, frontend/linki-user/src/components/user/influencer/mypage/MyPageReceivedReviews.vue, frontend/linki-user/src/components/user/influencer/mypage/MyPageWriteReview.vue, frontend/linki-user/src/components/user/influencer/mypage/MyPageWrittenReviews.vue, frontend/linki-user/src/utils/httpRequest.js, frontend/linki-user/src/views/user/influencer/CampaignListView.vue, frontend/linki-user/src/views/user/influencer/CampaignProposalView.vue, frontend/linki-user/src/views/user/influencer/Detail.vue
api 엔드포인트 수정
- v1/api/influencer 로 통일 
예상되는 영향이나 고민
=> ✨ feature : api 엔드포인트 수정

frontend/json-server/db.json, frontend/json-server/routes.json, frontend/linki-user/src/api/campaign.js, frontend/linki-user/src/views/user/influencer/CampaignListView.vue
캠페인 조회할때 카테고리 하드코딩 된거 제거하고 db.json에 있는 카테고리 불러오도록 수정 
- 한 일 1
- 한 일 2
예상되는 영향이나 고민
=> 🐛 fix : 캠페인 카테고리 조회 수정

frontend/linki-user/src/components/Sidebar.vue
헤더 확대되면 글씨 찌그러지는 오류 수정 
- 한 일 1
- 한 일 2
예상되는 영향이나 고민
=> 🐛 fix :헤더 수정

frontend/linki-user/src/components/Sidebar.vue
채팅 사이드바 밑으로 내려가는 오류 수정 
- 한 일 1
- 한 일 2
예상되는 영향이나 고민
=> 🐛 fix : 채팅 사이드바 수정

frontend/linki-user/src/api/subscription.js, frontend/linki-user/src/components/user/advertiser/mypage/MyPageSubscriptionApply.vue, frontend/linki-user/src/components/user/advertiser/mypage/MyPageSubscriptionManage.vue, frontend/linki-user/src/components/user/advertiser/mypage/MyPageSubscriptionRefund.vue, frontend/linki-user/src/views/user/advertiser/MyPage.vue
vue 구독관리 광고주 기능 프론트 작업
- 구독 신청 컴포넌트 구현
- 구독 현황 컴포넌트
- 구독 환불 컴포넌트
=> ✨ feature : 광고주 구독관리 프론트 작업

quries/tableInit.sql
TableInit.sql 추가
-TableInit.sql 추가
제일 상위 패키지에 quries/TableInit.sql 추가하였습니다.
계정 만드는 쿼리문도 만들어서
주석처리하였습니다.
필요하시면, 주석 처리 해제후 사용하시면 될거같습니다.
=> 🗃️ db : TableInit.sql 추가

admin-integration-service/build.gradle, admin-integration-service/src/main/java/com/linki/admin_integration_service/config/JwtInterceptor.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/config/JwtUtil.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/config/MyBatisConfig.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/config/WebConfig.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/exception/GlobalExceptionHandler.java, admin-integration-service/src/main/resources/application.properties
admin-config 추가
- MyBatis Config 추가
- Cors Config 추가
- JWT Interceptor 추가
- GlobalExceptionHandler 추가
=> ✨ feature : admin-config 추가

admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/operations/controller/AdvertiserReviewsController.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/operations/dto/AdvertiserResponseDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/operations/dto/AdvertiserReviewDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/operations/dto/AdvertiserReviewSearchRequestDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/operations/dto/AdvertiserReviewVisibilityRequestDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/operations/repository/jpa/AdvertiserReviewRepository.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/operations/repository/myBatis/AdvertiserReviewsMapper.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/operations/service/AdvertiserReviewsService.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/operations/service/AdvertiserReviewsServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/operations/service/InfluencerReviewsServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/entity/AdvertiserReview.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/queries/AdvertiserReviewsView.sql, admin-integration-service/src/main/resources/mapper/operations/advertiserReviews.xml, admin-integration-service/src/test/java/com/linki/admin_integration_service/operations/controller/adminAdvertiserReview.postman_test_run.json, admin-integration-service/src/test/java/com/linki/admin_integration_service/operations/repository/AdvertiserReviewsMapperTests.java, admin-integration-service/src/test/java/com/linki/admin_integration_service/operations/service/AdvertiserReviewsServiceTests.java, frontend/linki-admin/src/components/table/operations/AdvertiserReviewsTable.vue, frontend/linki-admin/src/js/operations/AdvertisersReviews.js
관리자 - 광고주 리뷰 기능 구현
- 관리자 - 광고주 리뷰 가져오기 기능 구현
- 관리자 - 광고주 리뷰 검색 기능 구현
- 관리자 - 광고주 리뷰 공개/비공개 기능 구현
=> ✨ feature : 관리자 - 광고주 리뷰 기능 구현

integration-service/src/main/java/com/Gritty/Linki/config/MyBatisConfig.java
jpa, mybatis 충돌 오류 수정, 패키지 구조 정리
- mybatisConfig에서 mapper 경로 수정 
- 인플루언서 패키지 구조 정리 
예상되는 영향이나 고민
=> 🐛 fix : jpa, mybatis 충돌 오류 수정, 패키지 구조 정리

integration-service/src/main/java/com/Gritty/Linki/config/MyBatisConfig.java
간단한 설명
- 한 일 1
- 한 일 2
예상되는 영향이나 고민
=> 🐛 fix : 패키지 gitkeep 추가 

integration-service/src/main/java/com/Gritty/Linki/config/MyBatisConfig.java, integration-service/src/main/java/com/Gritty/Linki/config/RestTemplateConfig.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/controller/ChannelController.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/controller/YouTubeChannelController.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/dto/YouTubeChannelDto.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/dto/YouTubeSearchDto.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/repository/ChannelRepository.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/repository/jpa/ChannelJpaRepository.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/repository/jpa/ChannelSearchRepository.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/request/ChannelSearchRequest.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/response/ChannelListResponse.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/service/ChannelService.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/service/YouTubeApiService.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/service/YouTubeChannelCollectService.java, integration-service/src/main/java/com/Gritty/Linki/entity/AdvertiserReview.java, integration-service/src/main/java/com/Gritty/Linki/entity/Campaign.java, integration-service/src/main/java/com/Gritty/Linki/entity/Channel.java, integration-service/src/main/java/com/Gritty/Linki/entity/InfluencerReview.java, integration-service/src/main/java/com/Gritty/Linki/exception/ErrorCode.java, integration-service/src/main/java/com/Gritty/Linki/repository/InfluencerRepository.java, integration-service/src/main/resources/application.properties
✨ feature : Youtube data api 사용하여 유튜브 채널 데이터 수집 기능 추가 
[🐛 fix : 페이징 때문에 TRAVEL 채널 요청했을때 10개이상 존재함에도 불구하고 2개만 응답되는 현상 고침](https://github.com/team-gritty/linki/commit/e0317c1c2a124d74083f8d67dd9549d8c436839b)
예상되는 영향이나 고민
=> ✨ feature : Youtube data api 사용하여 유튜브 채널 데이터 수집 기능 추가 

admin-integration-service/src/main/java/com/linki/admin_integration_service/config/MyBatisConfig.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/user/controller/GeneralUserController.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/user/dto/GeneralUSerDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/user/dto/GeneralUserResponseDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/user/dto/GeneralUserSearchRequestDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/user/repository/myBatis/GeneralUserMapper.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/user/service/GeneralUserService.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/user/service/GeneralUserServiceImpl.java, admin-integration-service/src/test/java/com/linki/admin_integration_service/user/repository/GeneralUserMapperTests.java, admin-integration-service/src/test/java/com/linki/admin_integration_service/user/service/GeneralUserServiceTests.java, frontend/linki-admin/src/components/table/ user/GeneralUserTable.vue, frontend/linki-admin/src/js/user/GeneralUser.js
관리자 - 일반회원 조회 및 검색
- 관리자 - 광고주 일반회원 조회 기능 구현
- 관리자 - 광고주 일반회원 검색 기능 구현
=> ✨ feature : 관리자 - 일반회원 조회 및 검색

admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/user/controller/GeneralUserController.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/user/controller/SubscriberUserController.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/user/dto/SubscriberSearchRequestDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/user/dto/SubscriberUserDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/user/dto/SubscriberUserResponseDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/user/repository/myBatis/SubscriberUserMapper.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/user/service/SubscriberUserService.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/user/service/SubscriberUserServiceImpl.java, admin-integration-service/src/main/resources/mapper/user/SubscriberUser.xml, admin-integration-service/src/test/java/com/linki/admin_integration_service/user/controller/관리자 - 구독 회원.postman_test_run.json, admin-integration-service/src/test/java/com/linki/admin_integration_service/user/repository/SubscriberUserMapperTests.java, admin-integration-service/src/test/java/com/linki/admin_integration_service/user/service/SubscriberUserServiceTests.java, frontend/linki-admin/src/js/user/SubscriberUser.js
관리자 - 구독 회원 조회 및 검색
- 관리자 - 광고주 구독 회원 조회 기능 구현
- 관리자 - 광고주 구독 회원 검색 기능 구현
=> ✨ feature : 관리자 - 구독 회원 조회 및 검색

integration-service/src/main/java/com/Gritty/Linki/config/security/LoginFilter.java, integration-service/src/main/java/com/Gritty/Linki/config/security/SecurityConfig.java, integration-service/src/main/java/com/Gritty/Linki/domain/oAuth/signUp/controller/AccountController.java, integration-service/src/main/java/com/Gritty/Linki/domain/oAuth/signUp/repository/RefreshTokenRepository.java, integration-service/src/main/java/com/Gritty/Linki/domain/oAuth/signUp/service/RefreshTokenService.java, integration-service/src/main/java/com/Gritty/Linki/entity/RefreshToken.java, integration-service/src/main/java/com/Gritty/Linki/util/IdGenerator.java
리프레시 토큰, 로그아웃 구현
- 리프레시 토큰
- 로그아웃
예상되는 영향이나 고민
=> ✨ feature : 리프레시토큰, 로그아웃 구현

integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/AuthenticationUtil.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/proposal/controller/ProposalController.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/proposal/dto/ProposalDto.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/proposal/repository/ProposalRepository.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/proposal/request/ProposalAcceptRequest.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/proposal/request/ProposalRejectRequest.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/proposal/request/ProposalUpdateRequest.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/proposal/response/ProposalResponse.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/proposal/service/ProposalService.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/advertiser/repository/jpa/AdvertiserRepository.java, integration-service/src/main/java/com/Gritty/Linki/entity/Influencer.java, integration-service/src/main/java/com/Gritty/Linki/entity/Proposal.java, integration-service/src/main/java/com/Gritty/Linki/util/AuthenticationUtil.java, integration-service/src/test/java/com/Gritty/Linki/user/advertiser/proposal/ProposalServiceTests.java, integration-service/src/test/java/com/Gritty/Linki/user/advertiser/proposal/controller/acceptProposal.json, integration-service/src/test/java/com/Gritty/Linki/user/advertiser/proposal/controller/getProposalDetail.json, integration-service/src/test/java/com/Gritty/Linki/user/advertiser/proposal/controller/getProposalsByCampaign.json, integration-service/src/test/java/com/Gritty/Linki/user/advertiser/proposal/controller/rejectProposal.json, integration-service/src/test/java/com/Gritty/Linki/user/advertiser/proposal/controller/updateProposal.json, integration-service/src/test/java/com/Gritty/Linki/user/advertiser/proposal/repository/ProposalRepositoryTests.java, integration-service/src/test/java/com/Gritty/Linki/user/advertiser/proposal/service/ProposalServiceTests.java
✨ feature : 광고주 제안서 조회, 수정, 거절, 승낙 기능 추가 
✨ feature : 광고주 제안서 조회, 수정, 거절, 승낙 기능 추가 
[✨ feature : JWT CustomUserDetails에서 광고주 ID를 찾는 기능 추가](https://github.com/team-gritty/linki/commit/b7a455f116e9acef0f4b671a3dcf0b908590cc01)
[✅ test : 광고주 제안서 포스트맨 테스트 결과 추가](https://github.com/team-gritty/linki/commit/c3cf8f91f1bf3a689da7498a2f17d9b8d3565c9b)
예상되는 영향이나 고민
=> ✨ feature : 광고주 제안서 조회, 수정, 거절, 승낙 기능 추가 

admin-integration-service/src/main/java/com/linki/admin_integration_service/common/BaseSearchDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/config/MyBatisConfig.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/contract/controller/ContractController.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/contract/dto/ContractDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/contract/dto/ContractResponseDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/contract/dto/ContractSearchDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/contract/repository/myBatis/ContractMapper.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/contract/service/ContractService.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/contract/service/ContractServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/queries/ContractView.sql, admin-integration-service/src/main/resources/application.properties, admin-integration-service/src/main/resources/mapper/contract/Contracts.xml, admin-integration-service/src/test/java/com/linki/admin_integration_service/contract/controller/관리자 - 계약 조회.postman_test_run.json, admin-integration-service/src/test/java/com/linki/admin_integration_service/contract/repository/ContractMapperTests.java, admin-integration-service/src/test/java/com/linki/admin_integration_service/contract/service/ContractServiceTests.java, frontend/linki-admin/src/components/table/contract/ContractTable.vue, frontend/linki-admin/src/js/contract/Contract.js
관리자 - 계약 조회 및 검색
- 관리자 - 광고주 계약 조회 기능 구현
- 관리자 - 광고주 계약 검색 기능 구현
광고주 검색 불가 현상 해결
-> 원인 advertiser -> advertiserr 오타 issue....
=> ✨ feature : 관리자 - 계약 조회 및 검색

integration-service/src/main/java/com/Gritty/Linki/domain/user/influencer/campaign/service/InfluencerCampaignServiceImpl.java
dev랑 merge중 util 클래스 경로 잘못되어 수정해서 올립니다 
- 한 일 1
- 한 일 2
예상되는 영향이나 고민
=> 🐛 fix :fix/ util 경로 수정

admin-integration-service/src/main/java/com/linki/admin_integration_service/config/MyBatisConfig.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/payment/controller/PaymentSubscribeController.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/payment/dto/PaymentSubscribeDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/payment/dto/PaymentSubscribeResponseDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/payment/dto/PaymentSubscribeSearchDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/payment/repository/myBatis/PaymentSubscribeMapper.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/payment/service/PaymentSubscribeService.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/payment/service/PaymentSubscribeServiceImpl.java, admin-integration-service/src/main/resources/mapper/payment/PaymentSubscribe.xml, admin-integration-service/src/test/java/com/linki/admin_integration_service/payment/controller/관리자 - 구독 결제 관리.postman_test_run.json, admin-integration-service/src/test/java/com/linki/admin_integration_service/payment/repository/PaymentSubscribeMapperTest.java, admin-integration-service/src/test/java/com/linki/admin_integration_service/payment/service/PaymentSubscribeServiceTest.java, frontend/linki-admin/src/components/table/payment/SubscriptionPaymentTable.vue, frontend/linki-admin/src/js/payment/SubscriptionPayment.js
관리자 - 구독 결제 조회 및 검색
- 관리자 - 광고주 구독 결제 조회 기능 구현
- 관리자 - 광고주 구독 결제 검색 기능 구현
=> ✨ feature : 관리자 - 구독 결제 조회 및 검색

frontend/linki-user/src/components/user/advertiser/mypage/MyPageBasicInfo.vue, frontend/linki-user/src/components/user/general/mypage/MyPageBasicInfo.vue, frontend/linki-user/src/components/user/influencer/mypage/MyPageBasicInfo.vue
프론트 오류 수정 
- 한 일 1
- 한 일 2
예상되는 영향이나 고민
=> 🐛 fix : 프론트 오류 수정 

admin-integration-service/src/main/java/com/linki/admin_integration_service/config/MyBatisConfig.java, admin-integration-service/src/test/java/com/linki/admin_integration_service/operations/repository/InfluencerReviewsMapperTests.java, quries/dummydata.sql, quries/tableInit.sql
Db dummyData 변경
- Db dummyData 변경
=> 🗃️ db : Db dummyData 변경

frontend/linki-user/src/components/user/advertiser/mypage/MyPageBasicInfo.vue, frontend/linki-user/src/components/user/general/mypage/MyPageBasicInfo.vue, frontend/linki-user/src/components/user/influencer/mypage/MyPageBasicInfo.vue
axios 사용 httprequest 수정
- user, influencer, advertiser axios -> httprequest 수정
예상되는 영향이나 고민
=> 🐛 fix : axios 사용 httprequest 수정

frontend/linki-user/src/utils/httpRequest.js, integration-service/src/main/java/com/Gritty/Linki/config/security/JwtFilter.java, integration-service/src/main/java/com/Gritty/Linki/config/security/JwtUtil.java, integration-service/src/main/java/com/Gritty/Linki/domain/oAuth/account/controller/AccountController.java
액세스토큰 재발급 오류로 수정
- 액세스토큰 재발급 오류로 수정
- 한 일 2
예상되는 영향이나 고민
=> feature : 액세스토큰 재발급 수정 확인

admin-integration-service/src/main/java/com/linki/admin_integration_service/AdminIntegrationServiceApplication.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/common/redirect/repository/RedirectRepository.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/repository/ContractRepository.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/repository/InfluencerRepository.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/repository/LinkiScoreRepository.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/repository/ProposalRepository.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/repository/RedirectClickRepository.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/service/AverageReviewScoreService.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/service/AverageReviewScoreServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/service/CPCService.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/service/CPCServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/service/ContractCountService.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/service/ContractCountServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/service/DailyTrafficService.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/service/DailyTrafficServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/service/LinkiScoreService.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/service/LinkiScoreServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/operations/repository/jpa/AdminSignUpRepository.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/operations/repository/jpa/AdvertiserReviewRepository.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/operations/repository/jpa/InfluencerReviewRepository.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/entity/Contract.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/entity/Influencer.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/entity/InfluencerReview.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/entity/LinkiScore.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/entity/Proposal.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/entity/RedirectClick.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/entity/RedirectLinks.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/queries/LinkiScoreTable.sql, admin-integration-service/src/main/java/com/linki/admin_integration_service/util/IdGenerator.java, quries/LinkiScoreTable.sql
Linki Score 알고리즘 구현
- LinkiScore 알고리즘 구현
- 구현 방식 : https://small-ragdoll-a57.notion.site/LinkiScore-2173a719d35080d1902ff2402ab9c59d?pvs=74
현재 쓰레드 따로 할당하여 스프링 Application 실행후 10 초 후 @PostConstruct 실행
인플루언서 Sorting 기능을 위하여,
빠른 구현을 하여,  DB Reading이 빈번하여 속도 이슈 발생
싱글톤 캐싱 활용하여 속도 개선 예정
=> ✨ feature : Linki Score 알고리즘 구현

admin-integration-service/build.gradle, admin-integration-service/src/main/java/com/linki/admin_integration_service/common/redirect/controller/RedirectController.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/common/redirect/repository/RedirectRepository.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/common/redirect/service/RedirectServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/config/RetryConfig.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/repository/ContractRepository.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/repository/LinkiScoreRepository.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/service/AverageReviewScoreServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/service/CPCServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/service/ContractCountServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/service/LinkiScoreServiceImpl.java, quries/LinkiScoreTable.sql
LinkiScore 및 리다이렉트 속도개선
- LinkiScore 속도 개선
- 리다이렉트 속도 개선
=> ♻️ refactor : LinkiScore 및 리다이렉트 속도개선

frontend/linki-user/src/components/user/general/mypage/MyPageChannelChange.vue, frontend/linki-user/src/router/index.js, frontend/linki-user/src/views/common/GoogleCallback.vue, frontend/linki-user/src/views/user/general/MyPage.vue, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/DTO/AdvertiserRegisterRequest.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/DTO/OcrResultDTO.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/DTO/RequestDTO.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/DTO/ResponseDTO.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/controller/AdvertiserRegisterController.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/controller/bizCheckController.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/repository/AdvertiserRegisterRepository.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/service/AdvertiserRegisterService.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/service/AdvertiserRegisterServiceImpl.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/service/AiBizCheckService.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/service/AiBizCheckServiceImpl.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/service/BizCheckService.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/service/BizCheckServiceImpl.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/service/NtsBizCheckService.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/service/NtsBizCheckServiceImpl.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/service/OcrService.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/bizNumberCheck/service/OcrServiceImpl.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/controller/YoutubeController.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/dto/YoutubeApiResponse.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/dto/YoutubeChannelInfo.java, integration-service/src/main/java/com/Gritty/Linki/domain/user/mypage/service/YoutubeService.java, integration-service/src/main/java/com/Gritty/Linki/entity/User.java, integration-service/src/main/java/com/Gritty/Linki/repository/ChannelRepository.java, integration-service/src/main/resources/application.properties, integration-service/src/main/resources/bizNumber/bizNumber.json, quries/tableInit.sql
인플루언서 / 광고주 전환
- 인플루언서 전환
- 광고주 전환
예상되는 영향이나 고민
=> Feature : 인플루언서 전환

admin-integration-service/src/main/java/com/linki/admin_integration_service/config/SecurityConfig.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/account/controller/AccountController.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/account/dto/JoinDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/account/dto/RequestJoinDTO.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/account/repository/AccountRepository.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/account/service/AccountService.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/account/service/accountServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/entity/Admin.java, frontend/linki-user/src/components/user/general/mypage/MyPageChannelChange.vue, integration-service/src/main/resources/application.properties
인플루언서 카테고리 종류 value 설정
- 인플루언서 카테고리 종류 value 재설정
- 한 일 2
예상되는 영향이나 고민
=> fix : 인플루언서 카테고리 종류 value 설정

admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/service/AverageReviewScoreServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/linkiscore/service/LinkiScoreServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/operations/repository/jpa/InfluencerReviewRepository.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/entity/Proposal.java
linki score 예외 처리
- 리뷰가 없는 인플루언서 기본점수 부여
=> 🐛 fix : linki score 예외 처리

chat-service/src/main/java/com/ssg/chatservice/domain/chat/dto/ChatDTO.java, chat-service/src/main/java/com/ssg/chatservice/domain/chat/dto/respone/ChatResponeDTO.java, chat-service/src/main/java/com/ssg/chatservice/domain/chat/service/ChatServiceImpl.java, chat-service/src/main/java/com/ssg/chatservice/domain/notification/service/NotificationServiceImpl.java, frontend/linki-user/src/App.vue, frontend/linki-user/src/components/ChatDropdown.vue, frontend/linki-user/src/components/user/advertiser/detail/DetailChat.vue, frontend/linki-user/src/components/user/influencer/detail/DetailChat.vue, frontend/linki-user/src/stores/chat.js, frontend/linki-user/src/views/user/influencer/Detail.vue
채팅 동작 테스트 및 버그 제거
- 제안서 거절 시 ui 및 알람 추가
- 제안서/계약서 상태 변경 시 nego_status update
- 제안서 탭에 접속 중에 드롭다운(메신저)를 통해 해당 제안서의 채팅방에 접속하면 탭 이동이 되지 않는 버그 제거
- 채팅방 접속 중에도 알림 메세지 즉시 조회 
예상되는 영향이나 고민
=> 🐛 fix : chat servcie 동작 테스트 및 버그 제거

admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/dashboard/service/ContractStatusServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/dashboard/service/DashboardSummaryServiceImpl.java, admin-integration-service/src/main/java/com/linki/admin_integration_service/domain/dashboard/service/TrendChartServiceImpl.java, frontend/linki-admin/src/views/HomeView.vue
관리자 대시보드 수정
- 차트 2024,2025만 데이터 뿌리는거, 동적으로 연도 찾아서 뿌리게 변경
- Redis 한시간마다 강제 갱신 설정
=> 🐛 fix : 관리자 대시보드 수정
